namespace MinesServer.GameShit
{
    public enum CellType : byte
    {
        Gate = 30,
        EmptyVulc = 31,
        Empty = 32,
        EmptyWithTrace = 33,
        EmptyWithBigTrace = 34,
        Road = 35,
        FedRoad = 36,
        PackDoor = 37,
        PackEdge = 38,
        Poli = 39,
        BlackBoulder1 = 40,
        BlackBoulder2 = 41,
        BlackBoulder3 = 42,
        MetBoulder1 = 43,
        MetBoulder2 = 44,
        MetBoulder3 = 45,
        Quadro = 48,
        Opora = 49,
        AliveCyan = 50,
        AliveRed = 51,
        AliveViol = 52,
        AliveNigger = 53,
        AliveWhite = 54,
        AliveRainbow = 55,
        AliveBlue = 116,
        Green = 107,
        Blue = 109,
        Red = 108,
        Violet = 110,
        White = 111,
        Cyan = 112,
        XGreen = 71,
        XBlue = 72,
        XRed = 73,
        XViolet = 75,
        XCyan = 74,
        NiggerRock = 114,
        RedRock = 117
    }
}
